import Head from 'next/head'
import CardWithImage from '@/components/card'
import CurrentWeatherCard from '@/components/cardToday'
import styles from '../styles/index.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.entirePage}>
          <section className={styles.infoSquare}>
            <section className={styles.partLeft}>
              <CurrentWeatherCard></CurrentWeatherCard>
            </section>
            <section className={styles.partRight}>
              <CardWithImage></CardWithImage>
              <div className={styles.weekCardsContainer}>
              </div>
            </section>
          </section>
        </section>
      </main>
    </>
  )
}
