import { useState, useEffect } from 'react';
import Head from 'next/head';
import CurrentWeatherCard from '@/components/cardToday';
import CardWithImage from '@/components/card';
import styles from '../styles/index.module.css';

const API_KEY = '6b1d5ecb1b816eb86b1b035afb017936';

const Home = () => {
  const [weatherData, setWeatherData] = useState(null);

  useEffect(() => {
    const fetchWeatherData = async () => {
      try {
        const response = await fetch(
          `https://api.openweathermap.org/data/2.5/weather?q=Paris&appid=${API_KEY}&units=metric`
        );

        if (response.ok) {
          const data = await response.json();
          setWeatherData(data);
        } else {
          console.error('Erreur lors de la récupération des données météorologiques');
        }
      } catch (error) {
        console.error('Erreur réseau :', error);
      }
    };

    fetchWeatherData();
  }, []);

  return (
    <>
      <Head>
        <title>My Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.entirePage}>
          <section className={styles.infoSquare}>
            <section className={styles.partLeft}>
              <CurrentWeatherCard weatherData={weatherData} setCity={undefined} />
            </section>
            <section className={styles.partRight}>
              <CardWithImage />
              <div className={styles.weekCardsContainer}></div>
            </section>
          </section>
        </section>
      </main>
    </>
  );
};

export default Home;
