name: Mon Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Utiliser le secret
        run: echo "La valeur du secret est ${{ secrets.API_KEY }}"
